// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVBePY1Bwjs8v1sadS9SgqfvwL1sFvR4',
    appId: '1:213026914760:web:ff1894486140c6e48d40fd',
    messagingSenderId: '213026914760',
    projectId: 'routi-n',
    authDomain: 'routi-n.firebaseapp.com',
    storageBucket: 'routi-n.firebasestorage.app',
    measurementId: 'G-92357YWJ5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KE0gVAU-pbC55BNK04Uim6Q3bPn13-c',
    appId: '1:213026914760:android:1e8957359155d4068d40fd',
    messagingSenderId: '213026914760',
    projectId: 'routi-n',
    storageBucket: 'routi-n.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8V_y9ALKLoNXWdMCShcUrJYSVdZRFaQ',
    appId: '1:213026914760:ios:67b76760620868778d40fd',
    messagingSenderId: '213026914760',
    projectId: 'routi-n',
    storageBucket: 'routi-n.firebasestorage.app',
    iosBundleId: 'com.example.routin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVBePY1Bwjs8v1sadS9SgqfvwL1sFvR4',
    appId: '1:213026914760:web:00204e808ee535708d40fd',
    messagingSenderId: '213026914760',
    projectId: 'routi-n',
    authDomain: 'routi-n.firebaseapp.com',
    storageBucket: 'routi-n.firebasestorage.app',
    measurementId: 'G-BCRT4LM5GB',
  );
}
